Chaos Error (most recent call last):
File: "~/chaos/__interactive__.kaos", line 23
print f5(3)
File: "~/chaos/__interactive__.kaos", line 20
y == 2 : f6(y)
File: "~/chaos/__interactive__.kaos", line 12
y == 1 : f7()
File: "~/chaos/tests/shell/modules/lib.kaos", line 4
print a[4]
Index out of range: 4 for the list!
Absorbed by Interactive Shell
